name = "Oil"
license = "MIT"
licenselink = "https://github.com/khsing/hugo-theme-oil/blob/master/LICENSE"
description = "Simple blog theme."
homepage = "https://github.com/khsing/hugo-theme-oil"
tags = ["blog"]
features = ["mobile","elegant"]
min_version = "0.1.0"

[author]
  name = "khsing"
  homepage = "https://blog.khsing.net/"


# If porting an existing theme
[original]
  name = "amazingrise"
  homepage = "https://amazingrise.net/"
  repo = "https://github.com/amazingrise/hugo-theme-diary"
